name: testing github action

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.18.x

    - uses: actions/checkout@v2
    - name: Test 
      run: go test main_test.go 
        